### ISSUE TITLE
Custom DNS for VPN-on-Demand

### ISSUE THREAD

**Issue by dean-github** [nerd-one/VPN-OnDemand#10]
Hi all,
Can you please advise if we can set custom DNS like a Google DNS in this mobileconfig xml file?
Some VPN apps have this option in their apps' settings.
I'm not sure if this is possible, so any hint would be highly appreciated. 

Thank  you.
Dean

**Comment by nerd-one** [comment]
Hey Dean,

You can specify dns servers if vpn type is set to IKEv2.
I quickly added this to the .mobileconfig file(untested).

Feel free to leave a comment if it works.

Kind regards,
Florian

**Comment by dean-github** [comment]
Hi Florian,
Thanks for the update. I downloaded the updated .mobileconfig file, removed the ipsec section to test ikev2 only. 
But it doesn't work yet. After installing the profile, inside Configuration Profiles' "VPN OnDemand" section, it says "Contains Unknown Payload".
Therefore it doesn't appear in VPN list for connection.
Can you please try it on your side to see if anything missing?

Thank you again.

**Comment by nerd-one** [comment]
Thanks for testing. I failed to add the necessary DNS dictionary

Did this and moved it to the top of each VPN configuration (IKEv2/IPSec) – yes, it should work with IPSec as well, as I saw doing some research

Hopefully you can use it now

**Comment by dean-github** [comment]
Excellent! Thank you very much.
