### ISSUE TITLE
Application Based Demand

### ISSUE THREAD

**Issue by martinorob** [nerd-one/VPN-OnDemand#7]
Hi,
great work! Is there a way to establish a vpn connection if an app is open in foreground?
Like PRTG app.

Example: If I open PRTG app, iOS establish a vpn connection with the office.

Thanks

**Comment by nerd-one** [comment]
Hey, thank you very much.

To establish a trigger, based on the mentioned rule set.

If you know the URL, the app calls when opening, just use the action  'EvaluateConnection' and  'ConnectIfNeeded' with the corresponding URL value as trigger.

Hope, this help.
Regards, Florian
