### ISSUE TITLE
Lines 131 and 318 “any other WiFi” should be “a Cellular”

### ISSUE THREAD

**Issue by MSSEsq** [nerd-one/VPN-OnDemand#8]
https://github.com/nerd-one/VPN-OnDemand/blob/bca089cda8e0d33c0653e9d33960a0bccaa6b160/VPN%20OnDemand.mobileconfig#L131
This line should be: `<!-- "Connect", "Disconnect", or "Ignore" if device is connected to a Cellular network -->`
https://github.com/nerd-one/VPN-OnDemand/blob/bca089cda8e0d33c0653e9d33960a0bccaa6b160/VPN%20OnDemand.mobileconfig#L318
This line should be: `<!-- "Connect", "Disconnect", or "Ignore" if device is connected to a Cellular network -->`

**Comment by nerd-one** [comment]
Thank you very much for correcting.
