### ISSUE TITLE
Current Configuration Profile Reference URL

### ISSUE THREAD

**Issue by MSSEsq** [nerd-one/VPN-OnDemand#9]
https://github.com/nerd-one/VPN-OnDemand/blob/bca089cda8e0d33c0653e9d33960a0bccaa6b160/VPN%20OnDemand.mobileconfig#L5
The current Configuration Profile Reference URL is: https://developer.apple.com/enterprise/documentation/Configuration-Profile-Reference.pdf

**Comment by nerd-one** [comment]
Thank you very much for updating the URL.
